/**
 * 058 — `App.tsx` 조립의 소스 계약 (일기 모두 지우기·모듈 용량).
 *
 * 계약: specs/058-settings-this-phone/contracts/this-phone.md AF1~AF3·HS6
 *
 * 조립부는 기기 통로와 화면 겹이 얽혀 jest로 그리기 어렵다 — 「무엇을 어떤 순서·조건에서 하는가」를 소스에서 잠근다
 * (주석을 걷은 뒤).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(__dirname, "..", "..");
const strip = (source: string) => source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, "");
const APP = strip(readFileSync(join(ROOT, "App.tsx"), "utf8"));

function body(start: string, end: string): string {
  const from = APP.indexOf(start);
  expect(from).toBeGreaterThan(0);
  const to = APP.indexOf(end, from + start.length);
  expect(to).toBeGreaterThan(from);
  return APP.slice(from, to);
}

describe("AF1 — 요청 → 홈의 응답을 기다린 뒤에만 지운다", () => {
  it("stopHome: setWipeRequest → await ready 순서이고, requestWipe: await stopHome() → wipeDiaries( 순서다(059가 stopHome을 뽑았다)", () => {
    const stop = body("const stopHome = useCallback(", "}, []);");
    const request = stop.indexOf("setWipeRequest(");
    const wait = stop.indexOf("await ready");
    expect(request).toBeGreaterThan(0);
    expect(wait).toBeGreaterThan(request);

    const fn = body("const requestWipe = useCallback(", "}, [goHome, stopHome]);");
    const stopCall = fn.indexOf("await stopHome()");
    const wipe = fn.indexOf("wipeDiaries(");
    expect(stopCall).toBeGreaterThan(0);
    expect(wipe).toBeGreaterThan(stopCall);
  });

  it("응답은 기다리는 그 토큰일 때만 받는다", () => {
    expect(APP).toMatch(/if \(waiter === null \|\| waiter\.token !== token\) return;/);
  });
});

describe("AF2 — busy가 아니면 설정을 닫고 오늘로, 홈을 다시 마운트한다", () => {
  it("세 동작이 busy 조건 안에만 있다", () => {
    const fn = body("const requestWipe = useCallback(", "}, [goHome, stopHome]);");
    expect(fn).toMatch(
      /if \(outcome\.kind !== "busy"\) \{\s*goHome\(\);\s*setChosenDay\(dayOf\(new Date\(\)\)\);\s*setDiaryKey\(\(k\) => k \+ 1\);\s*\}/,
    );
    expect(APP.match(/setDiaryKey\(/g)).toHaveLength(1);
  });

  it("DiarySection의 key에 diaryKey가 들어간다", () => {
    expect(APP).toMatch(/key=\{`diary-\$\{autoGeneratedToken\}-\$\{diaryKey\}`\}/);
  });
});

describe("AF3 — 설정 조립부의 편수·용량", () => {
  const section = () => body("function SettingsSection(", "type SettingsValues");

  it("마운트 effect에서 용량과 편수를 한 번 읽는다", () => {
    expect(section()).toMatch(
      /readModuleBytes\(expoModelPorts\(\)\.files\)\s*\.then\(formatModuleBytes\)/,
    );
    expect(section()).toMatch(/diaryStore\s*\.listDays\(\)/);
  });

  it("행을 누르면 편수를 다시 세고 0보다 클 때만 대화상자를 연다", () => {
    const open = body("const onOpenWipe = useCallback(", "}, [diaryStore]);");
    expect(open).toMatch(/listDays\(\)/);
    expect(open).toMatch(/if \(count !== null && count > 0\) setWipeCount\(count\);/);
  });

  it("누를 수 있는가는 편수 > 0이고 지우는 중이 아닐 때다", () => {
    expect(section()).toMatch(/wipeEnabled=\{diaryCount !== null && diaryCount > 0 && !wiping\}/);
  });

  it("잠금에 막히면(busy) 막힘 줄을 켠다", () => {
    expect(section()).toMatch(/if \(outcome\.kind === "busy"\) setWipeBlocked\(true\);/);
  });
});

describe("HS6 — 요청은 언제나 홈이 받는다", () => {
  it("DiarySection은 DiaryHomeScreen 하나를 돌려주고 요청과 응답을 넘긴다", () => {
    const section = body("function DiarySection(", "async function readyCharacters(");
    expect(section.match(/return \(\s*</g)).toHaveLength(1);
    expect(section).toMatch(/<DiaryHomeScreen\b/);
    expect(section).toMatch(/wipeRequest=\{wipeRequest\}/);
    expect(section).toMatch(/onWipeReady=\{onWipeReady\}/);
  });
});
